(define (problem prob-dff97a38-e24d-4ef1-ab5c-3e2ff8a5656b)
    (:domain alpha)

    (:objects
        ais-broadcast-8 - root
        ais-overlay-27 - service
        ais-receiver-28 - service
        ais-situational-awareness-96 - root
        ais-target-reception-80 - root
        ais-transmitter-13 - service
        analog-nautical-chart-awareness-134 - child
        analog-propulsion-plant-monitoring-data-100 - child
        analog-rai-156 - child
        analog-route-monitoring-136 - child
        analog-ship-kinematics-awareness-135 - child
        analogue-echo-sounder-data-111 - child
        arpa-processor-41 - service
        asterix-data-format-converter-39 - service
        asterix-raw-data-stream-42 - root
        automatic-roti-104 - service
        autopilot-46 - digital
        base-chart-display-108 - service
        compass-94 - analog
        conventional-position-fix-120 - child
        conventional-target-tracking-54 - child
        conventional-voyage-planning-paper-91 - child
        digital-ais-broadcast-145 - child
        digital-nautical-chart-awareness-26 - child
        digital-propulsion-plant-monitoring-data-74 - child
        digital-rai-155 - child
        digital-rate-of-turn-106 - child
        digital-route-monitoring-138 - child
        digital-rudder-feedback-70 - service
        digital-ship-kinematics-awareness-137 - child
        digital-speed-measurement-15 - child
        digital-speed-sensor-16 - service
        digital-target-reception-29 - child
        digital-target-tracking-115 - child
        ecdis-a-30 - digital
        ecdis-b-31 - digital
        echo-sounder-113 - service
        echo-sounder-data-water-depth-measurement-107 - root
        electro-steering-gear-actuation-33 - child
        electronic-echo-sounder-data-112 - child
        electronic-heading-sensor-data-24 - child
        electronic-helm-order-input-21 - child
        electronic-position-fix-gnss-119 - child
        electronic-steering-control-system-44 - service
        electronic-voyage-planning-89 - child
        emergency-steering-position-23 - service
        engine-rpm-analog-101 - service
        engine-rpm-digital-72 - service
        gnss-receiver-118 - service
        gyro-compass-45 - service
        hand-lead-109 - service
        heading-control-system-17 - service
        heading-sensor-data-95 - root
        helm-a-128 - digital
        helm-b-127 - digital
        helm-order-input-20 - root
        lead-line-110 - analog
        local-helm-142 - analog
        lookout-55 - service
        magnetic-compass-97 - service
        manual-ais-broadcast-146 - child
        manual-rate-of-turn-152 - child
        manual-roti-calculation-93 - service
        manual-speed-estimation-1 - service
        manual-speed-measurement-151 - child
        manual-target-reception-149 - child
        manual-target-tracking-130 - child
        map-2 - analog
        mechanical-rudder-feedback-157 - service
        mechanical-steering-35 - service
        mechanical-steering-gear-actuation-34 - child
        mechanical-steering-transmission-22 - child
        nautical-chart-awareness-125 - root
        nautical-charts-92 - service
        optical-bearing-121 - service
        pelorus-124 - analog
        plan-position-indicator-ppi-radar-display-51 - service
        propulsion-plant-monitoring-data-75 - root
        radar-antenna-a-40 - digital
        radar-antenna-b-38 - digital
        radar-ppi-a-133 - digital
        radar-ppi-b-132 - digital
        radar-video-display-52 - child
        radiotelephone-148 - analog
        rate-of-turn-99 - root
        reflection-plotter-131 - service
        route-controller-32 - service
        route-monitoring-11 - root
        route-planner-139 - service
        rtu-nmea-ai-a-14 - digital
        rtu-nmea-ai-b-12 - digital
        rtu-nmea-gp-a-123 - digital
        rtu-nmea-gp-b-122 - digital
        rtu-nmea-he-a-236 - digital
        rtu-nmea-he-b-242 - digital
        rtu-nmea-ii-a-73 - digital
        rtu-nmea-ii-b-71 - digital
        rtu-nmea-ra-a-153 - digital
        rtu-nmea-ra-b-154 - digital
        rtu-nmea-sd-a-117 - digital
        rtu-nmea-sd-b-116 - digital
        rtu-nmea-ti-a-105 - digital
        rtu-nmea-ti-b-103 - digital
        rudder-angle-indicator-feedback-129 - root
        rudder-indicator-158 - analog
        sgs-actuation-36 - root
        sgs-fluid-level-monitoring-50 - root
        sgs-master-a-465 - digital
        sgs-master-b-480 - digital
        sgs-master-controller-18 - service
        sgs-oil-1-490 - digital
        sgs-oil-2-493 - digital
        sgs-oil-monitoring-48 - root
        sgs-oil-sensor-49 - service
        sgs-oil-tank-level-140 - service
        sgs-oiltank-502 - digital
        sgs-pump-1-505 - digital
        sgs-pump-2-514 - digital
        sgs-pump-controller-47 - service
        shaft-37 - analog
        ship-kinematics-awareness-126 - root
        ship-rendering-25 - service
        speed-measurement-81 - root
        steering-gear-actuation-5 - root
        synchro-analogue-heading-sensor-data-98 - child
        tachometer-102 - analog
        target-tracking-114 - root
        targets-awareness-53 - root
        track-control-system-tcs-19 - service
        vessel-position-fix-3 - root
        vhf-dsc-controller-147 - service
        vhf-voice-watch-150 - service
        visual-watch-141 - analog
        voyage-planning-90 - root
    )

    (:init
        (can-be-hosted ais-overlay-27 ecdis-a-30)
        (can-be-hosted ais-overlay-27 ecdis-b-31)
        (can-be-hosted ais-receiver-28 rtu-nmea-ai-a-14)
        (can-be-hosted ais-receiver-28 rtu-nmea-ai-b-12)
        (can-be-hosted ais-transmitter-13 rtu-nmea-ai-a-14)
        (can-be-hosted ais-transmitter-13 rtu-nmea-ai-b-12)
        (can-be-hosted arpa-processor-41 rtu-nmea-ra-a-153)
        (can-be-hosted arpa-processor-41 rtu-nmea-ra-b-154)
        (can-be-hosted asterix-data-format-converter-39 radar-antenna-a-40)
        (can-be-hosted asterix-data-format-converter-39 radar-antenna-b-38)
        (can-be-hosted automatic-roti-104 rtu-nmea-ti-a-105)
        (can-be-hosted automatic-roti-104 rtu-nmea-ti-b-103)
        (can-be-hosted base-chart-display-108 ecdis-a-30)
        (can-be-hosted base-chart-display-108 ecdis-b-31)
        (can-be-hosted digital-rudder-feedback-70 rtu-nmea-ii-a-73)
        (can-be-hosted digital-rudder-feedback-70 rtu-nmea-ii-b-71)
        (can-be-hosted digital-speed-sensor-16 rtu-nmea-ii-a-73)
        (can-be-hosted digital-speed-sensor-16 rtu-nmea-ii-b-71)
        (can-be-hosted echo-sounder-113 rtu-nmea-sd-a-117)
        (can-be-hosted echo-sounder-113 rtu-nmea-sd-b-116)
        (can-be-hosted electronic-steering-control-system-44 helm-a-128)
        (can-be-hosted electronic-steering-control-system-44 helm-b-127)
        (can-be-hosted emergency-steering-position-23 local-helm-142)
        (can-be-hosted engine-rpm-analog-101 tachometer-102)
        (can-be-hosted engine-rpm-digital-72 rtu-nmea-ii-a-73)
        (can-be-hosted engine-rpm-digital-72 rtu-nmea-ii-b-71)
        (can-be-hosted gnss-receiver-118 rtu-nmea-gp-a-123)
        (can-be-hosted gnss-receiver-118 rtu-nmea-gp-b-122)
        (can-be-hosted gyro-compass-45 rtu-nmea-he-a-236)
        (can-be-hosted gyro-compass-45 rtu-nmea-he-b-242)
        (can-be-hosted hand-lead-109 lead-line-110)
        (can-be-hosted heading-control-system-17 autopilot-46)
        (can-be-hosted lookout-55 visual-watch-141)
        (can-be-hosted magnetic-compass-97 compass-94)
        (can-be-hosted manual-roti-calculation-93 compass-94)
        (can-be-hosted manual-speed-estimation-1 map-2)
        (can-be-hosted mechanical-rudder-feedback-157 rudder-indicator-158)
        (can-be-hosted mechanical-steering-35 shaft-37)
        (can-be-hosted nautical-charts-92 map-2)
        (can-be-hosted optical-bearing-121 pelorus-124)
        (can-be-hosted plan-position-indicator-ppi-radar-display-51 radar-ppi-a-133)
        (can-be-hosted plan-position-indicator-ppi-radar-display-51 radar-ppi-b-132)
        (can-be-hosted reflection-plotter-131 visual-watch-141)
        (can-be-hosted route-controller-32 ecdis-a-30)
        (can-be-hosted route-controller-32 ecdis-b-31)
        (can-be-hosted route-planner-139 ecdis-a-30)
        (can-be-hosted route-planner-139 ecdis-b-31)
        (can-be-hosted sgs-master-controller-18 sgs-master-a-465)
        (can-be-hosted sgs-master-controller-18 sgs-master-b-480)
        (can-be-hosted sgs-oil-sensor-49 sgs-oil-1-490)
        (can-be-hosted sgs-oil-sensor-49 sgs-oil-2-493)
        (can-be-hosted sgs-oil-tank-level-140 sgs-oiltank-502)
        (can-be-hosted sgs-pump-controller-47 sgs-pump-1-505)
        (can-be-hosted sgs-pump-controller-47 sgs-pump-2-514)
        (can-be-hosted ship-rendering-25 ecdis-a-30)
        (can-be-hosted ship-rendering-25 ecdis-b-31)
        (can-be-hosted track-control-system-tcs-19 autopilot-46)
        (can-be-hosted vhf-dsc-controller-147 radiotelephone-148)
        (can-be-hosted vhf-voice-watch-150 radiotelephone-148)
        (can-be-provided ais-broadcast-8 ais-transmitter-13)
        (can-be-provided ais-broadcast-8 vhf-dsc-controller-147)
        (can-be-provided ais-situational-awareness-96 ais-overlay-27)
        (can-be-provided ais-target-reception-80 ais-receiver-28)
        (can-be-provided ais-target-reception-80 vhf-voice-watch-150)
        (can-be-provided analog-nautical-chart-awareness-134 nautical-charts-92)
        (can-be-provided analog-propulsion-plant-monitoring-data-100 engine-rpm-analog-101)
        (can-be-provided analog-rai-156 mechanical-rudder-feedback-157)
        (can-be-provided analog-route-monitoring-136 nautical-charts-92)
        (can-be-provided analog-ship-kinematics-awareness-135 nautical-charts-92)
        (can-be-provided asterix-raw-data-stream-42 asterix-data-format-converter-39)
        (can-be-provided conventional-position-fix-120 optical-bearing-121)
        (can-be-provided conventional-target-tracking-54 lookout-55)
        (can-be-provided conventional-voyage-planning-paper-91 nautical-charts-92)
        (can-be-provided digital-ais-broadcast-145 ais-transmitter-13)
        (can-be-provided digital-nautical-chart-awareness-26 base-chart-display-108)
        (can-be-provided digital-propulsion-plant-monitoring-data-74 engine-rpm-digital-72)
        (can-be-provided digital-rai-155 digital-rudder-feedback-70)
        (can-be-provided digital-rate-of-turn-106 automatic-roti-104)
        (can-be-provided digital-rate-of-turn-106 gyro-compass-45)
        (can-be-provided digital-route-monitoring-138 route-controller-32)
        (can-be-provided digital-ship-kinematics-awareness-137 ship-rendering-25)
        (can-be-provided digital-speed-measurement-15 digital-speed-sensor-16)
        (can-be-provided digital-speed-measurement-15 gnss-receiver-118)
        (can-be-provided digital-target-reception-29 ais-receiver-28)
        (can-be-provided digital-target-tracking-115 arpa-processor-41)
        (can-be-provided echo-sounder-data-water-depth-measurement-107 base-chart-display-108)
        (can-be-provided echo-sounder-data-water-depth-measurement-107 echo-sounder-113)
        (can-be-provided electro-steering-gear-actuation-33 sgs-master-controller-18)
        (can-be-provided electronic-echo-sounder-data-112 base-chart-display-108)
        (can-be-provided electronic-echo-sounder-data-112 echo-sounder-113)
        (can-be-provided electronic-heading-sensor-data-24 gnss-receiver-118)
        (can-be-provided electronic-heading-sensor-data-24 gyro-compass-45)
        (can-be-provided electronic-helm-order-input-21 electronic-steering-control-system-44)
        (can-be-provided electronic-position-fix-gnss-119 gnss-receiver-118)
        (can-be-provided electronic-voyage-planning-89 route-planner-139)
        (can-be-provided heading-sensor-data-95 gnss-receiver-118)
        (can-be-provided heading-sensor-data-95 gyro-compass-45)
        (can-be-provided heading-sensor-data-95 magnetic-compass-97)
        (can-be-provided helm-order-input-20 electronic-steering-control-system-44)
        (can-be-provided helm-order-input-20 emergency-steering-position-23)
        (can-be-provided manual-ais-broadcast-146 vhf-dsc-controller-147)
        (can-be-provided manual-rate-of-turn-152 manual-roti-calculation-93)
        (can-be-provided manual-speed-measurement-151 manual-speed-estimation-1)
        (can-be-provided manual-target-reception-149 vhf-voice-watch-150)
        (can-be-provided manual-target-tracking-130 lookout-55)
        (can-be-provided manual-target-tracking-130 reflection-plotter-131)
        (can-be-provided mechanical-steering-gear-actuation-34 mechanical-steering-35)
        (can-be-provided mechanical-steering-transmission-22 emergency-steering-position-23)
        (can-be-provided nautical-chart-awareness-125 base-chart-display-108)
        (can-be-provided nautical-chart-awareness-125 nautical-charts-92)
        (can-be-provided propulsion-plant-monitoring-data-75 engine-rpm-analog-101)
        (can-be-provided propulsion-plant-monitoring-data-75 engine-rpm-digital-72)
        (can-be-provided radar-video-display-52 plan-position-indicator-ppi-radar-display-51)
        (can-be-provided rate-of-turn-99 automatic-roti-104)
        (can-be-provided rate-of-turn-99 gyro-compass-45)
        (can-be-provided rate-of-turn-99 manual-roti-calculation-93)
        (can-be-provided route-monitoring-11 nautical-charts-92)
        (can-be-provided route-monitoring-11 route-controller-32)
        (can-be-provided rudder-angle-indicator-feedback-129 digital-rudder-feedback-70)
        (can-be-provided rudder-angle-indicator-feedback-129 mechanical-rudder-feedback-157)
        (can-be-provided sgs-actuation-36 sgs-pump-controller-47)
        (can-be-provided sgs-fluid-level-monitoring-50 sgs-oil-tank-level-140)
        (can-be-provided sgs-oil-monitoring-48 sgs-oil-sensor-49)
        (can-be-provided ship-kinematics-awareness-126 nautical-charts-92)
        (can-be-provided ship-kinematics-awareness-126 ship-rendering-25)
        (can-be-provided speed-measurement-81 digital-speed-sensor-16)
        (can-be-provided speed-measurement-81 gnss-receiver-118)
        (can-be-provided speed-measurement-81 manual-speed-estimation-1)
        (can-be-provided steering-gear-actuation-5 mechanical-steering-35)
        (can-be-provided steering-gear-actuation-5 sgs-master-controller-18)
        (can-be-provided synchro-analogue-heading-sensor-data-98 magnetic-compass-97)
        (can-be-provided target-tracking-114 arpa-processor-41)
        (can-be-provided target-tracking-114 lookout-55)
        (can-be-provided target-tracking-114 reflection-plotter-131)
        (can-be-provided targets-awareness-53 lookout-55)
        (can-be-provided targets-awareness-53 plan-position-indicator-ppi-radar-display-51)
        (can-be-provided vessel-position-fix-3 gnss-receiver-118)
        (can-be-provided vessel-position-fix-3 optical-bearing-121)
        (can-be-provided voyage-planning-90 nautical-charts-92)
        (can-be-provided voyage-planning-90 route-planner-139)
        (capability-can-inherit-criticality asterix-raw-data-stream-42)
        (capability-can-inherit-criticality digital-nautical-chart-awareness-26)
        (capability-can-inherit-criticality digital-speed-measurement-15)
        (capability-can-inherit-criticality digital-target-reception-29)
        (capability-can-inherit-criticality electronic-heading-sensor-data-24)
        (capability-can-inherit-criticality electronic-helm-order-input-21)
        (capability-can-inherit-criticality electronic-position-fix-gnss-119)
        (capability-can-inherit-criticality electronic-voyage-planning-89)
        (capability-can-inherit-criticality mechanical-steering-transmission-22)
        (capability-can-inherit-criticality radar-video-display-52)
        (capability-can-inherit-criticality sgs-actuation-36)
        (capability-can-inherit-criticality sgs-fluid-level-monitoring-50)
        (capability-can-inherit-criticality sgs-oil-monitoring-48)
        (capability-can-inherit-criticality synchro-analogue-heading-sensor-data-98)
        (context-critical ais-broadcast-8)
        (context-critical ais-situational-awareness-96)
        (context-critical ais-target-reception-80)
        (context-critical echo-sounder-data-water-depth-measurement-107)
        (context-critical heading-sensor-data-95)
        (context-critical helm-order-input-20)
        (context-critical nautical-chart-awareness-125)
        (context-critical propulsion-plant-monitoring-data-75)
        (context-critical rate-of-turn-99)
        (context-critical route-monitoring-11)
        (context-critical rudder-angle-indicator-feedback-129)
        (context-critical ship-kinematics-awareness-126)
        (context-critical speed-measurement-81)
        (context-critical steering-gear-actuation-5)
        (context-critical target-tracking-114)
        (context-critical targets-awareness-53)
        (context-critical vessel-position-fix-3)
        (has-clean-image autopilot-46)
        (has-clean-image ecdis-a-30)
        (has-clean-image ecdis-b-31)
        (has-clean-image helm-a-128)
        (has-clean-image helm-b-127)
        (has-clean-image radar-antenna-a-40)
        (has-clean-image radar-antenna-b-38)
        (has-clean-image radar-ppi-a-133)
        (has-clean-image radar-ppi-b-132)
        (has-clean-image rtu-nmea-ai-a-14)
        (has-clean-image rtu-nmea-ai-b-12)
        (has-clean-image rtu-nmea-gp-a-123)
        (has-clean-image rtu-nmea-gp-b-122)
        (has-clean-image rtu-nmea-he-a-236)
        (has-clean-image rtu-nmea-he-b-242)
        (has-clean-image rtu-nmea-ii-a-73)
        (has-clean-image rtu-nmea-ii-b-71)
        (has-clean-image rtu-nmea-ra-a-153)
        (has-clean-image rtu-nmea-ra-b-154)
        (has-clean-image rtu-nmea-sd-a-117)
        (has-clean-image rtu-nmea-sd-b-116)
        (has-clean-image rtu-nmea-ti-a-105)
        (has-clean-image rtu-nmea-ti-b-103)
        (has-clean-image sgs-master-a-465)
        (has-clean-image sgs-master-b-480)
        (has-clean-image sgs-oil-1-490)
        (has-clean-image sgs-oil-2-493)
        (has-clean-image sgs-oiltank-502)
        (has-clean-image sgs-pump-1-505)
        (has-clean-image sgs-pump-2-514)
        (host-can-be-critical ecdis-a-30)
        (host-can-be-critical ecdis-b-31)
        (host-can-be-critical helm-a-128)
        (host-can-be-critical helm-b-127)
        (host-can-be-critical radar-antenna-a-40)
        (host-can-be-critical radar-antenna-b-38)
        (host-can-be-critical radar-ppi-a-133)
        (host-can-be-critical radar-ppi-b-132)
        (host-can-be-critical rtu-nmea-ai-a-14)
        (host-can-be-critical rtu-nmea-ai-b-12)
        (host-can-be-critical rtu-nmea-gp-a-123)
        (host-can-be-critical rtu-nmea-gp-b-122)
        (host-can-be-critical rtu-nmea-he-a-236)
        (host-can-be-critical rtu-nmea-he-b-242)
        (host-can-be-critical rtu-nmea-ii-a-73)
        (host-can-be-critical rtu-nmea-ii-b-71)
        (host-can-be-critical rtu-nmea-ra-a-153)
        (host-can-be-critical rtu-nmea-ra-b-154)
        (host-can-be-critical rtu-nmea-sd-a-117)
        (host-can-be-critical rtu-nmea-sd-b-116)
        (host-can-be-critical rtu-nmea-ti-a-105)
        (host-can-be-critical rtu-nmea-ti-b-103)
        (host-can-be-critical sgs-master-a-465)
        (host-can-be-critical sgs-master-b-480)
        (host-can-be-critical sgs-oil-1-490)
        (host-can-be-critical sgs-oil-2-493)
        (host-can-be-critical sgs-oiltank-502)
        (host-can-be-critical sgs-pump-1-505)
        (host-can-be-critical sgs-pump-2-514)
        (is-compromised ecdis-b-31)
        (is-compromised radar-antenna-a-40)
        (is-compromised radar-ppi-a-133)
        (is-hosted-on ais-overlay-27 ecdis-a-30)
        (is-hosted-on ais-receiver-28 rtu-nmea-ai-a-14)
        (is-hosted-on ais-transmitter-13 rtu-nmea-ai-a-14)
        (is-hosted-on arpa-processor-41 rtu-nmea-ra-a-153)
        (is-hosted-on asterix-data-format-converter-39 radar-antenna-a-40)
        (is-hosted-on automatic-roti-104 rtu-nmea-ti-a-105)
        (is-hosted-on base-chart-display-108 ecdis-a-30)
        (is-hosted-on digital-rudder-feedback-70 rtu-nmea-ii-a-73)
        (is-hosted-on digital-speed-sensor-16 rtu-nmea-ii-a-73)
        (is-hosted-on echo-sounder-113 rtu-nmea-sd-a-117)
        (is-hosted-on electronic-steering-control-system-44 helm-a-128)
        (is-hosted-on emergency-steering-position-23 local-helm-142)
        (is-hosted-on engine-rpm-analog-101 tachometer-102)
        (is-hosted-on engine-rpm-digital-72 rtu-nmea-ii-a-73)
        (is-hosted-on gnss-receiver-118 rtu-nmea-gp-a-123)
        (is-hosted-on gyro-compass-45 rtu-nmea-he-a-236)
        (is-hosted-on hand-lead-109 lead-line-110)
        (is-hosted-on heading-control-system-17 autopilot-46)
        (is-hosted-on lookout-55 visual-watch-141)
        (is-hosted-on magnetic-compass-97 compass-94)
        (is-hosted-on manual-roti-calculation-93 compass-94)
        (is-hosted-on manual-speed-estimation-1 map-2)
        (is-hosted-on mechanical-rudder-feedback-157 rudder-indicator-158)
        (is-hosted-on mechanical-steering-35 shaft-37)
        (is-hosted-on nautical-charts-92 map-2)
        (is-hosted-on optical-bearing-121 pelorus-124)
        (is-hosted-on plan-position-indicator-ppi-radar-display-51 radar-ppi-a-133)
        (is-hosted-on reflection-plotter-131 visual-watch-141)
        (is-hosted-on route-controller-32 ecdis-a-30)
        (is-hosted-on route-planner-139 ecdis-a-30)
        (is-hosted-on sgs-master-controller-18 sgs-master-a-465)
        (is-hosted-on sgs-oil-sensor-49 sgs-oil-1-490)
        (is-hosted-on sgs-oil-tank-level-140 sgs-oiltank-502)
        (is-hosted-on sgs-pump-controller-47 sgs-pump-1-505)
        (is-hosted-on ship-rendering-25 ecdis-a-30)
        (is-hosted-on track-control-system-tcs-19 autopilot-46)
        (is-hosted-on vhf-dsc-controller-147 radiotelephone-148)
        (is-hosted-on vhf-voice-watch-150 radiotelephone-148)
        (is-part-of analog-nautical-chart-awareness-134 nautical-chart-awareness-125)
        (is-part-of analog-propulsion-plant-monitoring-data-100 propulsion-plant-monitoring-data-75)
        (is-part-of analog-rai-156 rudder-angle-indicator-feedback-129)
        (is-part-of analog-route-monitoring-136 route-monitoring-11)
        (is-part-of analog-ship-kinematics-awareness-135 ship-kinematics-awareness-126)
        (is-part-of analogue-echo-sounder-data-111 echo-sounder-data-water-depth-measurement-107)
        (is-part-of conventional-position-fix-120 vessel-position-fix-3)
        (is-part-of conventional-target-tracking-54 targets-awareness-53)
        (is-part-of conventional-voyage-planning-paper-91 voyage-planning-90)
        (is-part-of digital-ais-broadcast-145 ais-broadcast-8)
        (is-part-of digital-nautical-chart-awareness-26 nautical-chart-awareness-125)
        (is-part-of digital-propulsion-plant-monitoring-data-74 propulsion-plant-monitoring-data-75)
        (is-part-of digital-rai-155 rudder-angle-indicator-feedback-129)
        (is-part-of digital-rate-of-turn-106 rate-of-turn-99)
        (is-part-of digital-route-monitoring-138 route-monitoring-11)
        (is-part-of digital-ship-kinematics-awareness-137 ship-kinematics-awareness-126)
        (is-part-of digital-speed-measurement-15 speed-measurement-81)
        (is-part-of digital-target-reception-29 ais-target-reception-80)
        (is-part-of digital-target-tracking-115 target-tracking-114)
        (is-part-of electro-steering-gear-actuation-33 steering-gear-actuation-5)
        (is-part-of electronic-echo-sounder-data-112 echo-sounder-data-water-depth-measurement-107)
        (is-part-of electronic-heading-sensor-data-24 heading-sensor-data-95)
        (is-part-of electronic-helm-order-input-21 helm-order-input-20)
        (is-part-of electronic-position-fix-gnss-119 vessel-position-fix-3)
        (is-part-of electronic-voyage-planning-89 voyage-planning-90)
        (is-part-of manual-ais-broadcast-146 ais-broadcast-8)
        (is-part-of manual-rate-of-turn-152 rate-of-turn-99)
        (is-part-of manual-speed-measurement-151 speed-measurement-81)
        (is-part-of manual-target-reception-149 ais-target-reception-80)
        (is-part-of manual-target-tracking-130 target-tracking-114)
        (is-part-of mechanical-steering-gear-actuation-34 steering-gear-actuation-5)
        (is-part-of mechanical-steering-transmission-22 helm-order-input-20)
        (is-part-of radar-video-display-52 targets-awareness-53)
        (is-part-of synchro-analogue-heading-sensor-data-98 heading-sensor-data-95)
        (is-powered-on autopilot-46)
        (is-powered-on ecdis-a-30)
        (is-powered-on ecdis-b-31)
        (is-powered-on helm-a-128)
        (is-powered-on helm-b-127)
        (is-powered-on radar-antenna-a-40)
        (is-powered-on radar-antenna-b-38)
        (is-powered-on radar-ppi-a-133)
        (is-powered-on radar-ppi-b-132)
        (is-powered-on rtu-nmea-ai-a-14)
        (is-powered-on rtu-nmea-ai-b-12)
        (is-powered-on rtu-nmea-gp-a-123)
        (is-powered-on rtu-nmea-gp-b-122)
        (is-powered-on rtu-nmea-he-a-236)
        (is-powered-on rtu-nmea-he-b-242)
        (is-powered-on rtu-nmea-ii-a-73)
        (is-powered-on rtu-nmea-ii-b-71)
        (is-powered-on rtu-nmea-ra-a-153)
        (is-powered-on rtu-nmea-ra-b-154)
        (is-powered-on rtu-nmea-sd-a-117)
        (is-powered-on rtu-nmea-sd-b-116)
        (is-powered-on rtu-nmea-ti-a-105)
        (is-powered-on rtu-nmea-ti-b-103)
        (is-powered-on sgs-master-a-465)
        (is-powered-on sgs-master-b-480)
        (is-powered-on sgs-oil-1-490)
        (is-powered-on sgs-oil-2-493)
        (is-powered-on sgs-oiltank-502)
        (is-powered-on sgs-pump-1-505)
        (is-powered-on sgs-pump-2-514)
        (provider-can-be-critical ais-overlay-27)
        (provider-can-be-critical ais-receiver-28)
        (provider-can-be-critical ais-transmitter-13)
        (provider-can-be-critical arpa-processor-41)
        (provider-can-be-critical automatic-roti-104)
        (provider-can-be-critical base-chart-display-108)
        (provider-can-be-critical digital-rudder-feedback-70)
        (provider-can-be-critical digital-speed-sensor-16)
        (provider-can-be-critical echo-sounder-113)
        (provider-can-be-critical electronic-steering-control-system-44)
        (provider-can-be-critical emergency-steering-position-23)
        (provider-can-be-critical engine-rpm-analog-101)
        (provider-can-be-critical engine-rpm-digital-72)
        (provider-can-be-critical gnss-receiver-118)
        (provider-can-be-critical gyro-compass-45)
        (provider-can-be-critical lookout-55)
        (provider-can-be-critical magnetic-compass-97)
        (provider-can-be-critical manual-roti-calculation-93)
        (provider-can-be-critical manual-speed-estimation-1)
        (provider-can-be-critical mechanical-rudder-feedback-157)
        (provider-can-be-critical mechanical-steering-35)
        (provider-can-be-critical nautical-charts-92)
        (provider-can-be-critical optical-bearing-121)
        (provider-can-be-critical plan-position-indicator-ppi-radar-display-51)
        (provider-can-be-critical reflection-plotter-131)
        (provider-can-be-critical route-controller-32)
        (provider-can-be-critical sgs-master-controller-18)
        (provider-can-be-critical ship-rendering-25)
        (provider-can-be-critical vhf-dsc-controller-147)
        (provider-can-be-critical vhf-voice-watch-150)
        (provider-can-inherit-criticality asterix-data-format-converter-39)
        (provider-can-inherit-criticality route-planner-139)
        (provider-can-inherit-criticality sgs-oil-sensor-49)
        (provider-can-inherit-criticality sgs-oil-tank-level-140)
        (provider-can-inherit-criticality sgs-pump-controller-47)
        (root-is-provided-by ais-broadcast-8 ais-transmitter-13)
        (root-is-provided-by ais-situational-awareness-96 ais-overlay-27)
        (root-is-provided-by ais-target-reception-80 ais-receiver-28)
        (root-is-provided-by asterix-raw-data-stream-42 asterix-data-format-converter-39)
        (root-is-provided-by echo-sounder-data-water-depth-measurement-107 echo-sounder-113)
        (root-is-provided-by heading-sensor-data-95 gyro-compass-45)
        (root-is-provided-by helm-order-input-20 track-control-system-tcs-19)
        (root-is-provided-by nautical-chart-awareness-125 base-chart-display-108)
        (root-is-provided-by propulsion-plant-monitoring-data-75 engine-rpm-digital-72)
        (root-is-provided-by rate-of-turn-99 automatic-roti-104)
        (root-is-provided-by route-monitoring-11 route-controller-32)
        (root-is-provided-by rudder-angle-indicator-feedback-129 digital-rudder-feedback-70)
        (root-is-provided-by sgs-actuation-36 sgs-pump-controller-47)
        (root-is-provided-by sgs-fluid-level-monitoring-50 sgs-oil-tank-level-140)
        (root-is-provided-by sgs-oil-monitoring-48 sgs-oil-sensor-49)
        (root-is-provided-by ship-kinematics-awareness-126 ship-rendering-25)
        (root-is-provided-by speed-measurement-81 digital-speed-sensor-16)
        (root-is-provided-by steering-gear-actuation-5 sgs-master-controller-18)
        (root-is-provided-by target-tracking-114 arpa-processor-41)
        (root-is-provided-by targets-awareness-53 plan-position-indicator-ppi-radar-display-51)
        (root-is-provided-by vessel-position-fix-3 gnss-receiver-118)
        (root-is-provided-by voyage-planning-90 route-planner-139)
        (transitively-requires ais-overlay-27 digital-nautical-chart-awareness-26)
        (transitively-requires ais-overlay-27 digital-target-reception-29)
        (transitively-requires ais-transmitter-13 digital-speed-measurement-15)
        (transitively-requires ais-transmitter-13 electronic-heading-sensor-data-24)
        (transitively-requires ais-transmitter-13 electronic-position-fix-gnss-119)
        (transitively-requires arpa-processor-41 asterix-raw-data-stream-42)
        (transitively-requires arpa-processor-41 electronic-heading-sensor-data-24)
        (transitively-requires heading-control-system-17 digital-rate-of-turn-106)
        (transitively-requires heading-control-system-17 digital-speed-measurement-15)
        (transitively-requires heading-control-system-17 electronic-heading-sensor-data-24)
        (transitively-requires manual-roti-calculation-93 heading-sensor-data-95)
        (transitively-requires manual-speed-estimation-1 synchro-analogue-heading-sensor-data-98)
        (transitively-requires manual-speed-estimation-1 vessel-position-fix-3)
        (transitively-requires mechanical-steering-35 mechanical-steering-transmission-22)
        (transitively-requires optical-bearing-121 synchro-analogue-heading-sensor-data-98)
        (transitively-requires plan-position-indicator-ppi-radar-display-51 asterix-raw-data-stream-42)
        (transitively-requires reflection-plotter-131 asterix-raw-data-stream-42)
        (transitively-requires reflection-plotter-131 heading-sensor-data-95)
        (transitively-requires reflection-plotter-131 radar-video-display-52)
        (transitively-requires route-controller-32 digital-nautical-chart-awareness-26)
        (transitively-requires route-controller-32 electronic-voyage-planning-89)
        (transitively-requires sgs-master-controller-18 electronic-helm-order-input-21)
        (transitively-requires sgs-master-controller-18 sgs-actuation-36)
        (transitively-requires sgs-master-controller-18 sgs-fluid-level-monitoring-50)
        (transitively-requires sgs-master-controller-18 sgs-oil-monitoring-48)
        (transitively-requires sgs-pump-controller-47 sgs-fluid-level-monitoring-50)
        (transitively-requires sgs-pump-controller-47 sgs-oil-monitoring-48)
        (transitively-requires ship-rendering-25 digital-nautical-chart-awareness-26)
        (transitively-requires ship-rendering-25 digital-speed-measurement-15)
        (transitively-requires ship-rendering-25 electronic-heading-sensor-data-24)
        (transitively-requires ship-rendering-25 electronic-position-fix-gnss-119)
        (transitively-requires track-control-system-tcs-19 digital-nautical-chart-awareness-26)
        (transitively-requires track-control-system-tcs-19 digital-rate-of-turn-106)
        (transitively-requires track-control-system-tcs-19 digital-route-monitoring-138)
        (transitively-requires track-control-system-tcs-19 digital-speed-measurement-15)
        (transitively-requires track-control-system-tcs-19 electronic-heading-sensor-data-24)
        (transitively-requires track-control-system-tcs-19 electronic-position-fix-gnss-119)
        (transitively-requires track-control-system-tcs-19 electronic-voyage-planning-89)
        (= (cost-failover ais-overlay-27 ecdis-a-30) 1)
        (= (cost-failover ais-overlay-27 ecdis-b-31) 1)
        (= (cost-failover ais-receiver-28 rtu-nmea-ai-a-14) 1)
        (= (cost-failover ais-receiver-28 rtu-nmea-ai-b-12) 1)
        (= (cost-failover ais-transmitter-13 rtu-nmea-ai-a-14) 1)
        (= (cost-failover ais-transmitter-13 rtu-nmea-ai-b-12) 1)
        (= (cost-failover arpa-processor-41 rtu-nmea-ra-a-153) 1)
        (= (cost-failover arpa-processor-41 rtu-nmea-ra-b-154) 1)
        (= (cost-failover asterix-data-format-converter-39 radar-antenna-a-40) 1)
        (= (cost-failover asterix-data-format-converter-39 radar-antenna-b-38) 1)
        (= (cost-failover automatic-roti-104 rtu-nmea-ti-a-105) 1)
        (= (cost-failover automatic-roti-104 rtu-nmea-ti-b-103) 1)
        (= (cost-failover base-chart-display-108 ecdis-a-30) 0)
        (= (cost-failover base-chart-display-108 ecdis-b-31) 0)
        (= (cost-failover digital-rudder-feedback-70 rtu-nmea-ii-a-73) 1)
        (= (cost-failover digital-rudder-feedback-70 rtu-nmea-ii-b-71) 1)
        (= (cost-failover digital-speed-sensor-16 rtu-nmea-ii-a-73) 1)
        (= (cost-failover digital-speed-sensor-16 rtu-nmea-ii-b-71) 1)
        (= (cost-failover echo-sounder-113 rtu-nmea-sd-a-117) 1)
        (= (cost-failover echo-sounder-113 rtu-nmea-sd-b-116) 1)
        (= (cost-failover electronic-steering-control-system-44 helm-a-128) 1)
        (= (cost-failover electronic-steering-control-system-44 helm-b-127) 1)
        (= (cost-failover emergency-steering-position-23 local-helm-142) 176)
        (= (cost-failover engine-rpm-analog-101 tachometer-102) 147)
        (= (cost-failover engine-rpm-digital-72 rtu-nmea-ii-a-73) 1)
        (= (cost-failover engine-rpm-digital-72 rtu-nmea-ii-b-71) 1)
        (= (cost-failover gnss-receiver-118 rtu-nmea-gp-a-123) 0)
        (= (cost-failover gnss-receiver-118 rtu-nmea-gp-b-122) 0)
        (= (cost-failover gyro-compass-45 rtu-nmea-he-a-236) 0)
        (= (cost-failover gyro-compass-45 rtu-nmea-he-b-242) 0)
        (= (cost-failover hand-lead-109 lead-line-110) 900)
        (= (cost-failover heading-control-system-17 autopilot-46) 1)
        (= (cost-failover lookout-55 visual-watch-141) 4)
        (= (cost-failover magnetic-compass-97 compass-94) 4)
        (= (cost-failover manual-roti-calculation-93 compass-94) 22)
        (= (cost-failover manual-speed-estimation-1 map-2) 321)
        (= (cost-failover mechanical-rudder-feedback-157 rudder-indicator-158) 113)
        (= (cost-failover mechanical-steering-35 shaft-37) 18)
        (= (cost-failover nautical-charts-92 map-2) 42)
        (= (cost-failover optical-bearing-121 pelorus-124) 169)
        (= (cost-failover plan-position-indicator-ppi-radar-display-51 radar-ppi-a-133) 1)
        (= (cost-failover plan-position-indicator-ppi-radar-display-51 radar-ppi-b-132) 1)
        (= (cost-failover reflection-plotter-131 visual-watch-141) 44)
        (= (cost-failover route-controller-32 ecdis-a-30) 1)
        (= (cost-failover route-controller-32 ecdis-b-31) 1)
        (= (cost-failover route-planner-139 ecdis-a-30) 1)
        (= (cost-failover route-planner-139 ecdis-b-31) 1)
        (= (cost-failover sgs-master-controller-18 sgs-master-a-465) 1)
        (= (cost-failover sgs-master-controller-18 sgs-master-b-480) 1)
        (= (cost-failover sgs-oil-sensor-49 sgs-oil-1-490) 1)
        (= (cost-failover sgs-oil-sensor-49 sgs-oil-2-493) 1)
        (= (cost-failover sgs-oil-tank-level-140 sgs-oiltank-502) 1)
        (= (cost-failover sgs-pump-controller-47 sgs-pump-1-505) 1)
        (= (cost-failover sgs-pump-controller-47 sgs-pump-2-514) 1)
        (= (cost-failover ship-rendering-25 ecdis-a-30) 1)
        (= (cost-failover ship-rendering-25 ecdis-b-31) 1)
        (= (cost-failover track-control-system-tcs-19 autopilot-46) 1)
        (= (cost-failover vhf-dsc-controller-147 radiotelephone-148) 176)
        (= (cost-failover vhf-voice-watch-150 radiotelephone-148) 176)
        (= (cost-isolate autopilot-46) 1)
        (= (cost-isolate ecdis-a-30) 0)
        (= (cost-isolate ecdis-b-31) 0)
        (= (cost-isolate helm-a-128) 1)
        (= (cost-isolate helm-b-127) 1)
        (= (cost-isolate radar-antenna-a-40) 1)
        (= (cost-isolate radar-antenna-b-38) 1)
        (= (cost-isolate radar-ppi-a-133) 1)
        (= (cost-isolate radar-ppi-b-132) 1)
        (= (cost-isolate rtu-nmea-ai-a-14) 1)
        (= (cost-isolate rtu-nmea-ai-b-12) 1)
        (= (cost-isolate rtu-nmea-gp-a-123) 0)
        (= (cost-isolate rtu-nmea-gp-b-122) 0)
        (= (cost-isolate rtu-nmea-he-a-236) 1)
        (= (cost-isolate rtu-nmea-he-b-242) 1)
        (= (cost-isolate rtu-nmea-ii-a-73) 0)
        (= (cost-isolate rtu-nmea-ii-b-71) 0)
        (= (cost-isolate rtu-nmea-ra-a-153) 1)
        (= (cost-isolate rtu-nmea-ra-b-154) 1)
        (= (cost-isolate rtu-nmea-sd-a-117) 1)
        (= (cost-isolate rtu-nmea-sd-b-116) 1)
        (= (cost-isolate rtu-nmea-ti-a-105) 1)
        (= (cost-isolate rtu-nmea-ti-b-103) 1)
        (= (cost-isolate sgs-master-a-465) 1)
        (= (cost-isolate sgs-master-b-480) 1)
        (= (cost-isolate sgs-oil-1-490) 1)
        (= (cost-isolate sgs-oil-2-493) 1)
        (= (cost-isolate sgs-oiltank-502) 1)
        (= (cost-isolate sgs-pump-1-505) 1)
        (= (cost-isolate sgs-pump-2-514) 1)
        (= (cost-power-on autopilot-46) 120)
        (= (cost-power-on ecdis-a-30) 240)
        (= (cost-power-on ecdis-b-31) 240)
        (= (cost-power-on helm-a-128) 120)
        (= (cost-power-on helm-b-127) 120)
        (= (cost-power-on radar-antenna-a-40) 240)
        (= (cost-power-on radar-antenna-b-38) 240)
        (= (cost-power-on radar-ppi-a-133) 240)
        (= (cost-power-on radar-ppi-b-132) 240)
        (= (cost-power-on rtu-nmea-ai-a-14) 20)
        (= (cost-power-on rtu-nmea-ai-b-12) 20)
        (= (cost-power-on rtu-nmea-gp-a-123) 20)
        (= (cost-power-on rtu-nmea-gp-b-122) 20)
        (= (cost-power-on rtu-nmea-he-a-236) 20)
        (= (cost-power-on rtu-nmea-he-b-242) 20)
        (= (cost-power-on rtu-nmea-ii-a-73) 20)
        (= (cost-power-on rtu-nmea-ii-b-71) 20)
        (= (cost-power-on rtu-nmea-ra-a-153) 20)
        (= (cost-power-on rtu-nmea-ra-b-154) 20)
        (= (cost-power-on rtu-nmea-sd-a-117) 20)
        (= (cost-power-on rtu-nmea-sd-b-116) 20)
        (= (cost-power-on rtu-nmea-ti-a-105) 20)
        (= (cost-power-on rtu-nmea-ti-b-103) 20)
        (= (cost-power-on sgs-master-a-465) 20)
        (= (cost-power-on sgs-master-b-480) 20)
        (= (cost-power-on sgs-oil-1-490) 20)
        (= (cost-power-on sgs-oil-2-493) 20)
        (= (cost-power-on sgs-oiltank-502) 20)
        (= (cost-power-on sgs-pump-1-505) 20)
        (= (cost-power-on sgs-pump-2-514) 20)
        (= (cost-power-on-recovery autopilot-46) 120)
        (= (cost-power-on-recovery ecdis-a-30) 239)
        (= (cost-power-on-recovery ecdis-b-31) 239)
        (= (cost-power-on-recovery helm-a-128) 120)
        (= (cost-power-on-recovery helm-b-127) 120)
        (= (cost-power-on-recovery radar-antenna-a-40) 240)
        (= (cost-power-on-recovery radar-antenna-b-38) 240)
        (= (cost-power-on-recovery radar-ppi-a-133) 240)
        (= (cost-power-on-recovery radar-ppi-b-132) 240)
        (= (cost-power-on-recovery rtu-nmea-ai-a-14) 20)
        (= (cost-power-on-recovery rtu-nmea-ai-b-12) 20)
        (= (cost-power-on-recovery rtu-nmea-gp-a-123) 19)
        (= (cost-power-on-recovery rtu-nmea-gp-b-122) 19)
        (= (cost-power-on-recovery rtu-nmea-he-a-236) 20)
        (= (cost-power-on-recovery rtu-nmea-he-b-242) 20)
        (= (cost-power-on-recovery rtu-nmea-ii-a-73) 19)
        (= (cost-power-on-recovery rtu-nmea-ii-b-71) 19)
        (= (cost-power-on-recovery rtu-nmea-ra-a-153) 20)
        (= (cost-power-on-recovery rtu-nmea-ra-b-154) 20)
        (= (cost-power-on-recovery rtu-nmea-sd-a-117) 20)
        (= (cost-power-on-recovery rtu-nmea-sd-b-116) 20)
        (= (cost-power-on-recovery rtu-nmea-ti-a-105) 20)
        (= (cost-power-on-recovery rtu-nmea-ti-b-103) 20)
        (= (cost-power-on-recovery sgs-master-a-465) 20)
        (= (cost-power-on-recovery sgs-master-b-480) 20)
        (= (cost-power-on-recovery sgs-oil-1-490) 20)
        (= (cost-power-on-recovery sgs-oil-2-493) 20)
        (= (cost-power-on-recovery sgs-oiltank-502) 20)
        (= (cost-power-on-recovery sgs-pump-1-505) 20)
        (= (cost-power-on-recovery sgs-pump-2-514) 20)
        (= (cost-power-on-recovery-unsafe autopilot-46) 160)
        (= (cost-power-on-recovery-unsafe ecdis-a-30) 279)
        (= (cost-power-on-recovery-unsafe ecdis-b-31) 279)
        (= (cost-power-on-recovery-unsafe helm-a-128) 160)
        (= (cost-power-on-recovery-unsafe helm-b-127) 160)
        (= (cost-power-on-recovery-unsafe radar-antenna-a-40) 280)
        (= (cost-power-on-recovery-unsafe radar-antenna-b-38) 280)
        (= (cost-power-on-recovery-unsafe radar-ppi-a-133) 280)
        (= (cost-power-on-recovery-unsafe radar-ppi-b-132) 280)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ai-a-14) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ai-b-12) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-gp-a-123) 59)
        (= (cost-power-on-recovery-unsafe rtu-nmea-gp-b-122) 59)
        (= (cost-power-on-recovery-unsafe rtu-nmea-he-a-236) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-he-b-242) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ii-a-73) 59)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ii-b-71) 59)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ra-a-153) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ra-b-154) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-sd-a-117) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-sd-b-116) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ti-a-105) 60)
        (= (cost-power-on-recovery-unsafe rtu-nmea-ti-b-103) 60)
        (= (cost-power-on-recovery-unsafe sgs-master-a-465) 60)
        (= (cost-power-on-recovery-unsafe sgs-master-b-480) 60)
        (= (cost-power-on-recovery-unsafe sgs-oil-1-490) 60)
        (= (cost-power-on-recovery-unsafe sgs-oil-2-493) 60)
        (= (cost-power-on-recovery-unsafe sgs-oiltank-502) 60)
        (= (cost-power-on-recovery-unsafe sgs-pump-1-505) 60)
        (= (cost-power-on-recovery-unsafe sgs-pump-2-514) 60)
        (= (cost-reconnect autopilot-46) 1)
        (= (cost-reconnect ecdis-a-30) 1)
        (= (cost-reconnect ecdis-b-31) 1)
        (= (cost-reconnect helm-a-128) 1)
        (= (cost-reconnect helm-b-127) 1)
        (= (cost-reconnect radar-antenna-a-40) 1)
        (= (cost-reconnect radar-antenna-b-38) 1)
        (= (cost-reconnect radar-ppi-a-133) 1)
        (= (cost-reconnect radar-ppi-b-132) 1)
        (= (cost-reconnect rtu-nmea-ai-a-14) 1)
        (= (cost-reconnect rtu-nmea-ai-b-12) 1)
        (= (cost-reconnect rtu-nmea-gp-a-123) 1)
        (= (cost-reconnect rtu-nmea-gp-b-122) 1)
        (= (cost-reconnect rtu-nmea-he-a-236) 1)
        (= (cost-reconnect rtu-nmea-he-b-242) 1)
        (= (cost-reconnect rtu-nmea-ii-a-73) 1)
        (= (cost-reconnect rtu-nmea-ii-b-71) 1)
        (= (cost-reconnect rtu-nmea-ra-a-153) 1)
        (= (cost-reconnect rtu-nmea-ra-b-154) 1)
        (= (cost-reconnect rtu-nmea-sd-a-117) 1)
        (= (cost-reconnect rtu-nmea-sd-b-116) 1)
        (= (cost-reconnect rtu-nmea-ti-a-105) 1)
        (= (cost-reconnect rtu-nmea-ti-b-103) 1)
        (= (cost-reconnect sgs-master-a-465) 1)
        (= (cost-reconnect sgs-master-b-480) 1)
        (= (cost-reconnect sgs-oil-1-490) 1)
        (= (cost-reconnect sgs-oil-2-493) 1)
        (= (cost-reconnect sgs-oiltank-502) 1)
        (= (cost-reconnect sgs-pump-1-505) 1)
        (= (cost-reconnect sgs-pump-2-514) 1)
        (= (cost-reconnect-recovery autopilot-46) 1)
        (= (cost-reconnect-recovery ecdis-a-30) 0)
        (= (cost-reconnect-recovery ecdis-b-31) 0)
        (= (cost-reconnect-recovery helm-a-128) 1)
        (= (cost-reconnect-recovery helm-b-127) 1)
        (= (cost-reconnect-recovery radar-antenna-a-40) 1)
        (= (cost-reconnect-recovery radar-antenna-b-38) 1)
        (= (cost-reconnect-recovery radar-ppi-a-133) 1)
        (= (cost-reconnect-recovery radar-ppi-b-132) 1)
        (= (cost-reconnect-recovery rtu-nmea-ai-a-14) 1)
        (= (cost-reconnect-recovery rtu-nmea-ai-b-12) 1)
        (= (cost-reconnect-recovery rtu-nmea-gp-a-123) 0)
        (= (cost-reconnect-recovery rtu-nmea-gp-b-122) 0)
        (= (cost-reconnect-recovery rtu-nmea-he-a-236) 1)
        (= (cost-reconnect-recovery rtu-nmea-he-b-242) 1)
        (= (cost-reconnect-recovery rtu-nmea-ii-a-73) 0)
        (= (cost-reconnect-recovery rtu-nmea-ii-b-71) 0)
        (= (cost-reconnect-recovery rtu-nmea-ra-a-153) 1)
        (= (cost-reconnect-recovery rtu-nmea-ra-b-154) 1)
        (= (cost-reconnect-recovery rtu-nmea-sd-a-117) 1)
        (= (cost-reconnect-recovery rtu-nmea-sd-b-116) 1)
        (= (cost-reconnect-recovery rtu-nmea-ti-a-105) 1)
        (= (cost-reconnect-recovery rtu-nmea-ti-b-103) 1)
        (= (cost-reconnect-recovery sgs-master-a-465) 1)
        (= (cost-reconnect-recovery sgs-master-b-480) 1)
        (= (cost-reconnect-recovery sgs-oil-1-490) 1)
        (= (cost-reconnect-recovery sgs-oil-2-493) 1)
        (= (cost-reconnect-recovery sgs-oiltank-502) 1)
        (= (cost-reconnect-recovery sgs-pump-1-505) 1)
        (= (cost-reconnect-recovery sgs-pump-2-514) 1)
        (= (cost-reconnect-recovery-unsafe autopilot-46) 41)
        (= (cost-reconnect-recovery-unsafe ecdis-a-30) 40)
        (= (cost-reconnect-recovery-unsafe ecdis-b-31) 40)
        (= (cost-reconnect-recovery-unsafe helm-a-128) 41)
        (= (cost-reconnect-recovery-unsafe helm-b-127) 41)
        (= (cost-reconnect-recovery-unsafe radar-antenna-a-40) 41)
        (= (cost-reconnect-recovery-unsafe radar-antenna-b-38) 41)
        (= (cost-reconnect-recovery-unsafe radar-ppi-a-133) 41)
        (= (cost-reconnect-recovery-unsafe radar-ppi-b-132) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ai-a-14) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ai-b-12) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-gp-a-123) 40)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-gp-b-122) 40)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-he-a-236) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-he-b-242) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ii-a-73) 40)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ii-b-71) 40)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ra-a-153) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ra-b-154) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-sd-a-117) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-sd-b-116) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ti-a-105) 41)
        (= (cost-reconnect-recovery-unsafe rtu-nmea-ti-b-103) 41)
        (= (cost-reconnect-recovery-unsafe sgs-master-a-465) 41)
        (= (cost-reconnect-recovery-unsafe sgs-master-b-480) 41)
        (= (cost-reconnect-recovery-unsafe sgs-oil-1-490) 41)
        (= (cost-reconnect-recovery-unsafe sgs-oil-2-493) 41)
        (= (cost-reconnect-recovery-unsafe sgs-oiltank-502) 41)
        (= (cost-reconnect-recovery-unsafe sgs-pump-1-505) 41)
        (= (cost-reconnect-recovery-unsafe sgs-pump-2-514) 41)
        (= (cost-rollback autopilot-46) 304)
        (= (cost-rollback ecdis-a-30) 60)
        (= (cost-rollback ecdis-b-31) 60)
        (= (cost-rollback helm-a-128) 222)
        (= (cost-rollback helm-b-127) 222)
        (= (cost-rollback radar-antenna-a-40) 592)
        (= (cost-rollback radar-antenna-b-38) 592)
        (= (cost-rollback radar-ppi-a-133) 492)
        (= (cost-rollback radar-ppi-b-132) 492)
        (= (cost-rollback rtu-nmea-ai-a-14) 40)
        (= (cost-rollback rtu-nmea-ai-b-12) 40)
        (= (cost-rollback rtu-nmea-gp-a-123) 29)
        (= (cost-rollback rtu-nmea-gp-b-122) 29)
        (= (cost-rollback rtu-nmea-he-a-236) 39)
        (= (cost-rollback rtu-nmea-he-b-242) 39)
        (= (cost-rollback rtu-nmea-ii-a-73) 30)
        (= (cost-rollback rtu-nmea-ii-b-71) 30)
        (= (cost-rollback rtu-nmea-ra-a-153) 50)
        (= (cost-rollback rtu-nmea-ra-b-154) 50)
        (= (cost-rollback rtu-nmea-sd-a-117) 49)
        (= (cost-rollback rtu-nmea-sd-b-116) 49)
        (= (cost-rollback rtu-nmea-ti-a-105) 50)
        (= (cost-rollback rtu-nmea-ti-b-103) 50)
        (= (cost-rollback sgs-master-a-465) 46)
        (= (cost-rollback sgs-master-b-480) 46)
        (= (cost-rollback sgs-oil-1-490) 59)
        (= (cost-rollback sgs-oil-2-493) 59)
        (= (cost-rollback sgs-oiltank-502) 59)
        (= (cost-rollback sgs-pump-1-505) 59)
        (= (cost-rollback sgs-pump-2-514) 59)
        (= (cost-rollback-unsafe autopilot-46) 344)
        (= (cost-rollback-unsafe ecdis-a-30) 100)
        (= (cost-rollback-unsafe ecdis-b-31) 100)
        (= (cost-rollback-unsafe helm-a-128) 262)
        (= (cost-rollback-unsafe helm-b-127) 262)
        (= (cost-rollback-unsafe radar-antenna-a-40) 632)
        (= (cost-rollback-unsafe radar-antenna-b-38) 632)
        (= (cost-rollback-unsafe radar-ppi-a-133) 532)
        (= (cost-rollback-unsafe radar-ppi-b-132) 532)
        (= (cost-rollback-unsafe rtu-nmea-ai-a-14) 80)
        (= (cost-rollback-unsafe rtu-nmea-ai-b-12) 80)
        (= (cost-rollback-unsafe rtu-nmea-gp-a-123) 69)
        (= (cost-rollback-unsafe rtu-nmea-gp-b-122) 69)
        (= (cost-rollback-unsafe rtu-nmea-he-a-236) 79)
        (= (cost-rollback-unsafe rtu-nmea-he-b-242) 79)
        (= (cost-rollback-unsafe rtu-nmea-ii-a-73) 70)
        (= (cost-rollback-unsafe rtu-nmea-ii-b-71) 70)
        (= (cost-rollback-unsafe rtu-nmea-ra-a-153) 90)
        (= (cost-rollback-unsafe rtu-nmea-ra-b-154) 90)
        (= (cost-rollback-unsafe rtu-nmea-sd-a-117) 89)
        (= (cost-rollback-unsafe rtu-nmea-sd-b-116) 89)
        (= (cost-rollback-unsafe rtu-nmea-ti-a-105) 90)
        (= (cost-rollback-unsafe rtu-nmea-ti-b-103) 90)
        (= (cost-rollback-unsafe sgs-master-a-465) 86)
        (= (cost-rollback-unsafe sgs-master-b-480) 86)
        (= (cost-rollback-unsafe sgs-oil-1-490) 99)
        (= (cost-rollback-unsafe sgs-oil-2-493) 99)
        (= (cost-rollback-unsafe sgs-oiltank-502) 99)
        (= (cost-rollback-unsafe sgs-pump-1-505) 99)
        (= (cost-rollback-unsafe sgs-pump-2-514) 99)
        (= (cost-shutdown autopilot-46) 30)
        (= (cost-shutdown ecdis-a-30) 59)
        (= (cost-shutdown ecdis-b-31) 59)
        (= (cost-shutdown helm-a-128) 30)
        (= (cost-shutdown helm-b-127) 30)
        (= (cost-shutdown radar-antenna-a-40) 60)
        (= (cost-shutdown radar-antenna-b-38) 60)
        (= (cost-shutdown radar-ppi-a-133) 60)
        (= (cost-shutdown radar-ppi-b-132) 60)
        (= (cost-shutdown rtu-nmea-ai-a-14) 2)
        (= (cost-shutdown rtu-nmea-ai-b-12) 2)
        (= (cost-shutdown rtu-nmea-gp-a-123) 1)
        (= (cost-shutdown rtu-nmea-gp-b-122) 1)
        (= (cost-shutdown rtu-nmea-he-a-236) 2)
        (= (cost-shutdown rtu-nmea-he-b-242) 2)
        (= (cost-shutdown rtu-nmea-ii-a-73) 1)
        (= (cost-shutdown rtu-nmea-ii-b-71) 1)
        (= (cost-shutdown rtu-nmea-ra-a-153) 2)
        (= (cost-shutdown rtu-nmea-ra-b-154) 2)
        (= (cost-shutdown rtu-nmea-sd-a-117) 2)
        (= (cost-shutdown rtu-nmea-sd-b-116) 2)
        (= (cost-shutdown rtu-nmea-ti-a-105) 2)
        (= (cost-shutdown rtu-nmea-ti-b-103) 2)
        (= (cost-shutdown sgs-master-a-465) 2)
        (= (cost-shutdown sgs-master-b-480) 2)
        (= (cost-shutdown sgs-oil-1-490) 2)
        (= (cost-shutdown sgs-oil-2-493) 2)
        (= (cost-shutdown sgs-oiltank-502) 2)
        (= (cost-shutdown sgs-pump-1-505) 2)
        (= (cost-shutdown sgs-pump-2-514) 2)
        (= (cost-switch ais-broadcast-8 ais-transmitter-13) 3)
        (= (cost-switch ais-broadcast-8 vhf-dsc-controller-147) 299)
        (= (cost-switch ais-situational-awareness-96 ais-overlay-27) 37)
        (= (cost-switch ais-target-reception-80 ais-receiver-28) 2)
        (= (cost-switch ais-target-reception-80 vhf-voice-watch-150) 899)
        (= (cost-switch asterix-raw-data-stream-42 asterix-data-format-converter-39) 5)
        (= (cost-switch echo-sounder-data-water-depth-measurement-107 base-chart-display-108) 297)
        (= (cost-switch echo-sounder-data-water-depth-measurement-107 echo-sounder-113) 2)
        (= (cost-switch heading-sensor-data-95 gnss-receiver-118) 2)
        (= (cost-switch heading-sensor-data-95 gyro-compass-45) 2)
        (= (cost-switch heading-sensor-data-95 magnetic-compass-97) 898)
        (= (cost-switch helm-order-input-20 electronic-steering-control-system-44) 30)
        (= (cost-switch helm-order-input-20 emergency-steering-position-23) 765)
        (= (cost-switch nautical-chart-awareness-125 base-chart-display-108) 21)
        (= (cost-switch nautical-chart-awareness-125 nautical-charts-92) 881)
        (= (cost-switch propulsion-plant-monitoring-data-75 engine-rpm-analog-101) 899)
        (= (cost-switch propulsion-plant-monitoring-data-75 engine-rpm-digital-72) 2)
        (= (cost-switch rate-of-turn-99 automatic-roti-104) 2)
        (= (cost-switch rate-of-turn-99 gyro-compass-45) 2)
        (= (cost-switch rate-of-turn-99 manual-roti-calculation-93) 899)
        (= (cost-switch route-monitoring-11 nautical-charts-92) 881)
        (= (cost-switch route-monitoring-11 route-controller-32) 31)
        (= (cost-switch rudder-angle-indicator-feedback-129 digital-rudder-feedback-70) 2)
        (= (cost-switch rudder-angle-indicator-feedback-129 mechanical-rudder-feedback-157) 898)
        (= (cost-switch sgs-actuation-36 sgs-pump-controller-47) 280)
        (= (cost-switch sgs-fluid-level-monitoring-50 sgs-oil-tank-level-140) 5)
        (= (cost-switch sgs-oil-monitoring-48 sgs-oil-sensor-49) 5)
        (= (cost-switch ship-kinematics-awareness-126 nautical-charts-92) 898)
        (= (cost-switch ship-kinematics-awareness-126 ship-rendering-25) 3)
        (= (cost-switch speed-measurement-81 digital-speed-sensor-16) 2)
        (= (cost-switch speed-measurement-81 gnss-receiver-118) 2)
        (= (cost-switch speed-measurement-81 manual-speed-estimation-1) 899)
        (= (cost-switch steering-gear-actuation-5 mechanical-steering-35) 782)
        (= (cost-switch steering-gear-actuation-5 sgs-master-controller-18) 165)
        (= (cost-switch target-tracking-114 arpa-processor-41) 3)
        (= (cost-switch target-tracking-114 lookout-55) 899)
        (= (cost-switch target-tracking-114 reflection-plotter-131) 899)
        (= (cost-switch targets-awareness-53 lookout-55) 881)
        (= (cost-switch targets-awareness-53 plan-position-indicator-ppi-radar-display-51) 26)
        (= (cost-switch vessel-position-fix-3 gnss-receiver-118) 2)
        (= (cost-switch vessel-position-fix-3 optical-bearing-121) 899)
        (= (cost-switch voyage-planning-90 nautical-charts-92) 899)
        (= (cost-switch voyage-planning-90 route-planner-139) 58)
        (= (penalty-active-threat autopilot-46) 44171)
        (= (penalty-active-threat ecdis-a-30) 44171)
        (= (penalty-active-threat ecdis-b-31) 44171)
        (= (penalty-active-threat helm-a-128) 44171)
        (= (penalty-active-threat helm-b-127) 44171)
        (= (penalty-active-threat radar-antenna-a-40) 44171)
        (= (penalty-active-threat radar-antenna-b-38) 44171)
        (= (penalty-active-threat radar-ppi-a-133) 44171)
        (= (penalty-active-threat radar-ppi-b-132) 44171)
        (= (penalty-active-threat rtu-nmea-ai-a-14) 44171)
        (= (penalty-active-threat rtu-nmea-ai-b-12) 44171)
        (= (penalty-active-threat rtu-nmea-gp-a-123) 44171)
        (= (penalty-active-threat rtu-nmea-gp-b-122) 44171)
        (= (penalty-active-threat rtu-nmea-he-a-236) 44171)
        (= (penalty-active-threat rtu-nmea-he-b-242) 44171)
        (= (penalty-active-threat rtu-nmea-ii-a-73) 44171)
        (= (penalty-active-threat rtu-nmea-ii-b-71) 44171)
        (= (penalty-active-threat rtu-nmea-ra-a-153) 44171)
        (= (penalty-active-threat rtu-nmea-ra-b-154) 44171)
        (= (penalty-active-threat rtu-nmea-sd-a-117) 44171)
        (= (penalty-active-threat rtu-nmea-sd-b-116) 44171)
        (= (penalty-active-threat rtu-nmea-ti-a-105) 44171)
        (= (penalty-active-threat rtu-nmea-ti-b-103) 44171)
        (= (penalty-active-threat sgs-master-a-465) 44171)
        (= (penalty-active-threat sgs-master-b-480) 44171)
        (= (penalty-active-threat sgs-oil-1-490) 44171)
        (= (penalty-active-threat sgs-oil-2-493) 44171)
        (= (penalty-active-threat sgs-oiltank-502) 44171)
        (= (penalty-active-threat sgs-pump-1-505) 44171)
        (= (penalty-active-threat sgs-pump-2-514) 44171)
        (= (penalty-existing-threat autopilot-46) 44171)
        (= (penalty-existing-threat ecdis-a-30) 44171)
        (= (penalty-existing-threat ecdis-b-31) 44171)
        (= (penalty-existing-threat helm-a-128) 44171)
        (= (penalty-existing-threat helm-b-127) 44171)
        (= (penalty-existing-threat radar-antenna-a-40) 44171)
        (= (penalty-existing-threat radar-antenna-b-38) 44171)
        (= (penalty-existing-threat radar-ppi-a-133) 44171)
        (= (penalty-existing-threat radar-ppi-b-132) 44171)
        (= (penalty-existing-threat rtu-nmea-ai-a-14) 44171)
        (= (penalty-existing-threat rtu-nmea-ai-b-12) 44171)
        (= (penalty-existing-threat rtu-nmea-gp-a-123) 44171)
        (= (penalty-existing-threat rtu-nmea-gp-b-122) 44171)
        (= (penalty-existing-threat rtu-nmea-he-a-236) 44171)
        (= (penalty-existing-threat rtu-nmea-he-b-242) 44171)
        (= (penalty-existing-threat rtu-nmea-ii-a-73) 44171)
        (= (penalty-existing-threat rtu-nmea-ii-b-71) 44171)
        (= (penalty-existing-threat rtu-nmea-ra-a-153) 44171)
        (= (penalty-existing-threat rtu-nmea-ra-b-154) 44171)
        (= (penalty-existing-threat rtu-nmea-sd-a-117) 44171)
        (= (penalty-existing-threat rtu-nmea-sd-b-116) 44171)
        (= (penalty-existing-threat rtu-nmea-ti-a-105) 44171)
        (= (penalty-existing-threat rtu-nmea-ti-b-103) 44171)
        (= (penalty-existing-threat sgs-master-a-465) 44171)
        (= (penalty-existing-threat sgs-master-b-480) 44171)
        (= (penalty-existing-threat sgs-oil-1-490) 44171)
        (= (penalty-existing-threat sgs-oil-2-493) 44171)
        (= (penalty-existing-threat sgs-oiltank-502) 44171)
        (= (penalty-existing-threat sgs-pump-1-505) 44171)
        (= (penalty-existing-threat sgs-pump-2-514) 44171)
        (= (penalty-unrecovered-host autopilot-46) 44171)
        (= (penalty-unrecovered-host ecdis-a-30) 44171)
        (= (penalty-unrecovered-host ecdis-b-31) 44171)
        (= (penalty-unrecovered-host helm-a-128) 44171)
        (= (penalty-unrecovered-host helm-b-127) 44171)
        (= (penalty-unrecovered-host radar-antenna-a-40) 44171)
        (= (penalty-unrecovered-host radar-antenna-b-38) 44171)
        (= (penalty-unrecovered-host radar-ppi-a-133) 44171)
        (= (penalty-unrecovered-host radar-ppi-b-132) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ai-a-14) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ai-b-12) 44171)
        (= (penalty-unrecovered-host rtu-nmea-gp-a-123) 44171)
        (= (penalty-unrecovered-host rtu-nmea-gp-b-122) 44171)
        (= (penalty-unrecovered-host rtu-nmea-he-a-236) 44171)
        (= (penalty-unrecovered-host rtu-nmea-he-b-242) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ii-a-73) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ii-b-71) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ra-a-153) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ra-b-154) 44171)
        (= (penalty-unrecovered-host rtu-nmea-sd-a-117) 44171)
        (= (penalty-unrecovered-host rtu-nmea-sd-b-116) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ti-a-105) 44171)
        (= (penalty-unrecovered-host rtu-nmea-ti-b-103) 44171)
        (= (penalty-unrecovered-host sgs-master-a-465) 44171)
        (= (penalty-unrecovered-host sgs-master-b-480) 44171)
        (= (penalty-unrecovered-host sgs-oil-1-490) 44171)
        (= (penalty-unrecovered-host sgs-oil-2-493) 44171)
        (= (penalty-unrecovered-host sgs-oiltank-502) 44171)
        (= (penalty-unrecovered-host sgs-pump-1-505) 44171)
        (= (penalty-unrecovered-host sgs-pump-2-514) 44171)
        (= (total-cost) 0)
    )

    (:goal
        (and
            (threat-contained radar-antenna-a-40)
            (threat-removed radar-antenna-a-40)
            (host-recovered radar-antenna-a-40)
            (threat-contained radar-ppi-a-133)
            (threat-removed radar-ppi-a-133)
            (host-recovered radar-ppi-a-133)
            (threat-contained ecdis-b-31)
            (threat-removed ecdis-b-31)
            (host-recovered ecdis-b-31)
            (is-available route-monitoring-11)
            (is-available heading-sensor-data-95)
            (is-available nautical-chart-awareness-125)
            (is-available targets-awareness-53)
            (is-available ais-situational-awareness-96)
            (is-available rudder-angle-indicator-feedback-129)
            (is-available ais-target-reception-80)
            (is-available speed-measurement-81)
            (is-available vessel-position-fix-3)
            (is-available steering-gear-actuation-5)
            (is-available ais-broadcast-8)
            (is-available target-tracking-114)
            (is-available ship-kinematics-awareness-126)
            (is-available helm-order-input-20)
            (is-available propulsion-plant-monitoring-data-75)
            (is-available rate-of-turn-99)
            (is-available echo-sounder-data-water-depth-measurement-107)
        )
    )

    (:metric minimize (total-cost))
)